---
abstract: 'Prevent content from being deflated'
author:
  - 'Olaf Alders <olaf@wundercounter.com>'
build_requires:
  English: 0
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102341, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-NoDeflate
requires:
  Plack::Middleware: 0
  parent: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Plack-Middleware-NoDeflate
  repository: http://github.com/oalders/Plack-Middleware-NoDeflate
version: 0.01
